In [3]:
import numpy as np
a=np.array([1,2,3,4])   #integer
a
a.dtype

dtype('int32')

In [2]:
b=np.array([True,False]) #boolean
b

array([ True, False])

In [4]:
b.dtype

dtype('bool')

In [5]:
c=np.array(['12345'])  #
c.dtype

dtype('<U5')

In [6]:
c

array(['12345'], dtype='<U5')

In [7]:
d=np.array([1.2,3.1,1,6,1.5]) #Float type integer
d

array([1.2, 3.1, 1. , 6. , 1.5])

In [8]:
d.dtype

dtype('float64')

In [19]:
e=np.array([1+2j, 2+3j])  #complex type
e
e.dtype

dtype('complex128')

In [20]:
f=np.timedelta64(5, 'D')    #timedelta
print(x)
f.dtype

[1.+2.j 2.+3.j 4.+5.j 5.+6.j]


dtype('<m8[D]')

In [2]:
import numpy as np     #datetime
g=np.array(['05-5-21','05-6-21','05-7-21','05-8-21'])
g

array(['05-5-21', '05-6-21', '05-7-21', '05-8-21'], dtype='<U7')

In [5]:
h=np.array([1,2,3,4,5,6],dtype='O')   #object
print(h, h.dtype)

[1 2 3 4 5 6] object


In [6]:
e=np.array(['H','I','T','H','E']) #string
e

array(['H', 'I', 'T', 'H', 'E'], dtype='<U1')

In [8]:
h=np.array([u'\24E',u'\31F'])      #Unicode string
h            

array(['\x14E', '\x19F'], dtype='<U2')